### ISSUE TITLE
Component - Playbar

### ISSUE THREAD

**Issue by MattheousDT** [feinwarusoftware/canary-desktop#1]
The user should be able to:

- [x] Play / Pause
- [x] Previous / Next song
- [x] Loop / Loop once
- [x] Shuffle
- [x] Adjust volume
- [x] See the progressed time
- [x] Progress through song using a standard bar or waveform *
- [x] Mute
- [x] Star music *
- [ ] Heart music *
- [ ] Adjust the colour of the bar and icons *

      * May require an additional component

![image](https://user-images.githubusercontent.com/28923903/59432615-a6f7ec80-8ddf-11e9-8c46-1c213bc54db1.png)

**Comment by Salies** [comment]
Closed issue. Heart (Last.fm) music and color/theme adjustment are things that will come back when I get to these features (Last.fm support and theme support).
